version: '3.9'

services:
  db:
    container_name: db
    image: postgres
    platform: linux/amd64
    restart: unless-stopped
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    ports:
      - $DB_PORT:5432

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "sleep 10s && npx prisma migrate deploy && node ./dist/main.js"
    restart: unless-stopped
    environment:
      - API_PORT=$API_PORT
      - DATABASE_URL=$DATABASE_URL
    ports:
      - '${API_PORT:-3000}:${API_PORT:-3000}'
    depends_on:
      - db

  ui:
    container_name: ui
    image: prostokosmos/test-ui
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - '8080:80'
    depends_on:
      - api

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    platform: linux/amd64
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-qwerty}
    ports:
      - '5050:80'
    depends_on:
      - db
